[package]
name = "simple-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
opentelemetry = "0.18.0"
opentelemetry-jaeger = "0.17.0"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
tracing-opentelemetry = "0.18.0"
