global:
  scrape_interval: 250ms # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 250ms # Evaluate rules every 15 seconds. The default is every 1 minute.

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'tempo'
    static_configs:
      - targets: ['tempo:3200']

  - job_name: 'oltp-metrics'
    static_configs:
      - targets: ['otel-collector:8889']
